# Generated by Django 5.1.7 on 2025-05-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sub_to_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
