# Generated by Django 5.1.7 on 2025-03-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
