# Generated by Django 5.1.7 on 2025-03-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_base_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
