# Generated by Django 5.1.7 on 2025-04-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_shape_base_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='number_per_sheet',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='material',
            name='cost_per_sheet',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
