# Generated by Django 5.1.7 on 2025-05-14 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_base_number_per_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shape'),
        ),
    ]
